POST   http://localhost:8000/api/products
Content-Type: application/json

{
  "name": "만든순서",
  "description": "123123",
  "price": 13,
  "tags": ["123"]
} 


###
GET http://localhost:8000/api/articles/
Content-Type: application/json


###
PATCH  http://localhost:8000/api/articles/67bc1255a227ecc60f2a7210
Content-Type: application/json

{
  "title": "수정완료",
  "content": "ㅇㄴㅇㄴㅇㄴㅇㄴ",
   "username": "너만보는늑대"
} 


###
PATCH  http://localhost:8000/api/articles/67bc461ea227ecc60f2a7d14/comments/67bc466ea227ecc60f2a7d91
Content-Type: application/json

{
  "content": "어머나다"
}